language: node_js
node_js:
    - "0.10"

before_script:
    - npm install
    - grunt compile

script: node_modules/karma/bin/karma start karma.conf.js --single-run

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install -g grunt-cli
    - npm install -g tsd
    - tsd install

