language: node_js
node_js:
  - "0.8"

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0

before_install: npm install -g grunt-cli
install: npm install

before_script:
    - grunt build

script:
    - phpunit
    - ./vendor/bin/phpcs --standard=PSR2 src